server:
  port: 9091
spring:
  application:
    name: student-service
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
      
      
 #actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'