server:
  port: 9091
spring:
  application:
    name: student-service
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
