student:
  URL: http://STUDENT-SERVICE/student/
server:
  port: 9092
spring:
  application:
    name: school-service
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
logging:
  level:
    '[com.school.app]': debug

    
 #actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
