student:
  URL: http://STUDENT-SERVICE/getstudent/school/
server:
  port: 9092
spring:
  application:
    name: school-service
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
logging:
  level:
    '[com.school.app]': debug