student:
  URL: http://localhost:9091/getstudent/school/
server:
  port: 9092
spring:
  application:
    name: school-service
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true