
spring:
   datasource:
     url: jdbc:mysql://localhost:3306/product?useSSL=false
     username: root
     password: root
   jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      dialect: org.hibernate.doalect.MYSQL8Dialect
      
server:
  port: 8081